const products = [
  {
    _id: "1",
    name: "Airpods wire",
    image: "/images/airpods.jpg",
    description: "Bluethooth technology lets you connect it with compatible",
    brand: "Apple",
    category: "Electronics",
    price: 934,
    counterInStock: 10,
    rating: 2.5,
    numReviews: 86,
  },
  {
    _id: "2",
    name: "Alexa works",
    image: "/images/alexa.jpg",
    description: "Bluethooth technology lets you connect it with compatible",
    brand: "Sumsung",
    category: "Electronics",
    price: 12934,
    counterInStock: 10,
    rating: 1.3,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Camera Buy",
    image: "/images/camera.jpg",
    description: "Bluethooth technology lets you connect it with compatible",
    brand: "Sony",
    category: "Automobile",
    price: 348,
    counterInStock: 10,
    rating: 5.1,
    numReviews: 14,
  },
  {
    _id: "4",
    name: "Amazon Echo Dot 3rd Generation",
    image: "/images/sample.jpg",
    description:
      "Meet Ecko Dot - Our most popular smart speaker with a good eye catching design,it is our most compact smart speaker",
    brand: "Amazon",
    category: "Electronics",
    price: 29.0,
    counterInStock: 0,
    rating: 5.1,
    numReviews: 28,
  },
  {
    _id: "5",
    name: "IPhone 11 Phone",
    image: "/images/phone.jpg",
    description:
      "Meet Ecko Dot - Our most popular smart speaker with a good eye catching design,it is our most compact smart speaker",
    brand: "Amazon",
    category: "Electronics",
    price: 2349.0,
    counterInStock: 9,
    rating: 5.1,
    numReviews: 28,
  },
];

export default products;
